SLACK_API_TOKEN: "xoxb-6567041518326-7037473636820-KUTMSWnPrV4X3ngn5oyOqr41"
SLACK_VERIFY_TOKEN: "VeZpxISb8b0yqZwxQr2OX5ol"
DISCORD_API_TOKEN: "MTIwMjg3ODc0MDA5OTc2ODM1MQ.GsHYhv.6LAmr-TwUDmDCQNGiDgNuaxqUUA3qVVlaSL0x4"
test_channel_id: "1202886521842049056"