SLACK_API_TOKEN: "xoxb-6567041518326-7049012801926-mCLkhUzkIrU0Mxk0lGWsPyiN"
SLACK_VERIFY_TOKEN: "GJSBi8Y2DMPhbglzVRL1tRWW"
DISCORD_API_TOKEN: "MTIwMjg3ODc0MDA5OTc2ODM1MQ.GsHYhv.6LAmr-TwUDmDCQNGiDgNuaxqUUA3qVVlaSL0x4"
test_channel_id: "1202886521842049056"